// Programa   : DPCLIENTESREC_TABLE
// Fecha/Hora : 10/02/2022 01:56:46
// Propósito  : Crear Tabla DPCLIENTESREC
// Creado Por :
// Llamado por:
// Aplicación :
// Tabla      :

#INCLUDE "DPXBASE.CH"

PROCE MAIN()

//  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_CODINV" ,"C",20,0,"Código de Producto","",NIL,NIL)
//  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_NUMMEM" ,"N",05,0,"Memo"              ,"",NIL,NIL)

  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_ACTIVO" ,'L',001,0,'Activo',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_CODCLI" ,'C',010,0,'Código Cliente',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_CODIGO" ,'C',010,0,'Código',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_CODINV" ,'C',020,0,'Producto',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_DESCUE" ,'N',006,2,'Descuento',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_DESDE"  ,'D',008,0,'Desde',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_DIAFRQ" ,'N',008,0,'Frecuencia',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_DIR1"   ,'C',100,0,'Dirección 1',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_DIR2"   ,'C',100,0,'Dirección 2',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_DIR3"   ,'C',100,0,'Dirección 3',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_EMAIL"  ,'C',120,0,'eMail',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_ESTADO" ,'C',001,0,'Activo,Suspendido,Inactivo',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_FCHINI" ,'D',008,0,'Inicio',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_FECHA"  ,'D',008,0,'Fecha',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_FILMAI" ,'N',010,0,'Registro Digitalización',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_ID"     ,'C',012,0,'Identificación',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_ITEM"   ,'C',003,0,'Item',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_MEMO"   ,'M',000,0,'Comentarios',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_NOMBRE" ,'C',200,0,'Nombre',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_NUMMEM" ,'N',005,0,'Memo',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_OBS1"   ,'C',250,0,'Comentario1',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_OBS2"   ,'C',250,0,'Comentario2',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_OBS3"   ,'C',250,0,'Comentario3',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_PARENT" ,'C',020,0,'Parentesco',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_SEXO"   ,'C',010,0,'Sexo',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_TEL1"   ,'C',012,0,'Teléfono',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_TIPO"   ,'C',040,0,'Tipo',"",NIL,NIL)
  EJECUTAR("DPCAMPOSADD","DPCLIENTESREC","CRC_CENCOS" ,'C',008,0,'Centro de Costo',"",NIL,NIL)

RETURN .T.
// EOF

